# 11-785 Recitation 0b: NumPy

$\hspace{5mm}$Sarveshwaran Dhanasekar - sarveshd@andrew.cmu.edu

## Introduction

- What is NumPy?
- What is vectorization?
- Why vectorization?

## Download and Installation

Follow instructions at https://scipy.org/install.html

## Introductory Example: Wx + b

### Naive Python Implementation

In [1]:
# Inputs
W = [[1, 1, 1],
     [2, 2, 2],
     [3, 3, 3]]

x = [7, 8, 5]
b = [1, 1, 1]

# Output
y = [0, 0, 0]

# Naive Computation of Wx + b
for i in range(len(W)):
    for j in range(len(x)):
        y[i] += W[i][j] * x[j]

for i in range(len(y)):
    y[i] += b[i]

y

[21, 41, 61]

### NumPy-based Vectorized Implementation

In [2]:
import numpy as np

In [3]:
W = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])
W

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [4]:
x = np.array([7, 8, 5])
x

array([7, 8, 5])

In [5]:
b = np.ones(3)
b

array([1., 1., 1.])

In [6]:
W.dot(x)

array([20, 40, 60])

In [7]:
W.dot(x) + b

array([21., 41., 61.])

## Multi-Dimensional Arrays

In [8]:
T = np.random.random((2,3,4))
T

array([[[0.35602633, 0.81967365, 0.01436362, 0.30507686],
        [0.57214146, 0.25681954, 0.54657445, 0.24565406],
        [0.09489982, 0.83035232, 0.21039348, 0.52688487]],

       [[0.09639595, 0.45579994, 0.97831089, 0.79952329],
        [0.26857038, 0.2883073 , 0.87237379, 0.34076551],
        [0.53070832, 0.64888004, 0.81278936, 0.53612879]]])

In [9]:
W = T[1]
W.shape, W.dtype

((3, 4), dtype('float64'))

In [10]:
X = np.full((4,3), 11785, dtype=np.int32)
X.shape, X.dtype

((4, 3), dtype('int32'))

In [11]:
W.dot(X)

array([[27459.40450912, 27459.40450912, 27459.40450912],
       [20859.65023864, 20859.65023864, 20859.65023864],
       [29798.4493526 , 29798.4493526 , 29798.4493526 ]])

In [12]:
X2 = np.zeros(X.shape)

np.array_equal(W.dot(X2), np.zeros((3,3)))

True

## Basic Element-wise Operations

In [13]:
y = np.arange(10)
y, np.array(range(10))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [14]:
y == np.array(range(10))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
y + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
y * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
(y + 1)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [18]:
y + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
y / (y + 1)

In [19]:
np.sqrt(y**2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
y.min(), y.max(), y.std(), y.sum()

(0, 9, 2.8722813232690143, 45)

## Indexing NumPy Arrays

In [21]:
np.save('tensor.npy', np.arange(2 * 4 * 4).reshape(2, 4, 4))

In [22]:
T = np.load('tensor.npy')
T,  T.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]]), (2, 4, 4))

In [23]:
T[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
T[1,0,0]  # more efficient version of T[1][0][0]

16

In [25]:
T[0,1:3,0:2]

array([[4, 5],
       [8, 9]])

In [26]:
(T % 10) == 0

array([[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [ True, False, False, False],
        [False, False, False, False],
        [False, False,  True, False]]])

In [27]:
T[(T % 10) == 0]

array([ 0, 10, 20, 30])

## Example: Masking and Clipping

In [28]:
W = np.random.randint(0, 10, (4, 4))
W

array([[0, 0, 2, 2],
       [9, 9, 0, 5],
       [2, 9, 9, 3],
       [2, 8, 5, 3]])

In [29]:
mask = np.ones_like(W)
mask[1] = 0
mask

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
W * mask

array([[0, 0, 2, 2],
       [0, 0, 0, 0],
       [2, 9, 9, 3],
       [2, 8, 5, 3]])

In [31]:
W > 5

array([[False, False, False, False],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [False,  True, False, False]])

In [32]:
W2 = W
W2[W2 > 5] = 5
W2

array([[0, 0, 2, 2],
       [5, 5, 0, 5],
       [2, 5, 5, 3],
       [2, 5, 5, 3]])

In [33]:
np.minimum(W, 5)

array([[0, 0, 2, 2],
       [5, 5, 0, 5],
       [2, 5, 5, 3],
       [2, 5, 5, 3]])

## Computation Along Axes

In [34]:
A = np.random.random((3,3))
A

array([[0.57581768, 0.27090377, 0.58548661],
       [0.45071023, 0.89006694, 0.6363428 ],
       [0.6163858 , 0.15057919, 0.7936273 ]])

In [35]:
A.sum()

4.9699203345292515

In [36]:
A.sum(axis=0)

array([1.64291371, 1.31154991, 2.01545671])

In [37]:
A.sum(axis=1)

array([1.43220806, 1.97711997, 1.5605923 ])

In [38]:
A.max(axis=0), A.argmax(axis=0)

(array([0.6163858 , 0.89006694, 0.7936273 ]), array([2, 1, 2]))

## Combining Arrays: Stacking & Concatenation

In [39]:
a = np.full(5, 1)
b = np.full(5, 2)
c = np.full(5, 3)
a, b, c

(array([1, 1, 1, 1, 1]), array([2, 2, 2, 2, 2]), array([3, 3, 3, 3, 3]))

Stacking creates a new axis. It joins the supplied arrays, which must have the same shape, along that axis.
Indexing a single element from that axis returns the appropriate input array.

In [40]:
B = np.stack([a, b, c], axis=1)
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (5, 3))

In [41]:
B[:,1]

array([2, 2, 2, 2, 2])

Concatenating arrays joins them along an *existing* aixs.

In [42]:
C = np.concatenate([B+100, B+200], axis=1)
C

array([[101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203]])

## Transposing and Reshaping

In [43]:
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (5, 3))

In [44]:
BT = B.T
BT, BT.shape

(array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]]), (3, 5))

In [45]:
BR = B.reshape(3, 5)
BR, BR.shape

(array([[1, 2, 3, 1, 2],
        [3, 1, 2, 3, 1],
        [2, 3, 1, 2, 3]]), (3, 5))

## Broadcasting

In [46]:
A = np.random.random((8, 4))
B = np.random.random((4, 3))
A.dot(B)

array([[0.90848635, 0.77342005, 0.93669621],
       [1.16466465, 0.98500075, 1.31866251],
       [1.45383224, 1.23347328, 1.58839386],
       [1.6832157 , 1.43096918, 1.74013402],
       [0.88148483, 0.75147901, 1.14501038],
       [0.79568081, 0.75609171, 1.09616815],
       [1.38120682, 1.29405594, 1.42669201],
       [1.61955182, 1.14034743, 1.58305158]])

In [47]:
b = np.array([10, 20, 30])
A.dot(B) + b

array([[10.90848635, 20.77342005, 30.93669621],
       [11.16466465, 20.98500075, 31.31866251],
       [11.45383224, 21.23347328, 31.58839386],
       [11.6832157 , 21.43096918, 31.74013402],
       [10.88148483, 20.75147901, 31.14501038],
       [10.79568081, 20.75609171, 31.09616815],
       [11.38120682, 21.29405594, 31.42669201],
       [11.61955182, 21.14034743, 31.58305158]])

Arrays must have same ending dimensions to broadcast.

In [48]:
print(np.arange(12).reshape((3,4)) + 0.01 * np.arange(4))
print(np.arange(8).reshape((2,4)) + 0.01 * np.arange(24).reshape((3,2,4)))
print(np.arange(6).reshape((3,1,2)) + 0.01 * np.arange(18).reshape((3,3,2)))

[[ 0.    1.01  2.02  3.03]
 [ 4.    5.01  6.02  7.03]
 [ 8.    9.01 10.02 11.03]]
[[[0.   1.01 2.02 3.03]
  [4.04 5.05 6.06 7.07]]

 [[0.08 1.09 2.1  3.11]
  [4.12 5.13 6.14 7.15]]

 [[0.16 1.17 2.18 3.19]
  [4.2  5.21 6.22 7.23]]]
[[[0.   1.01]
  [0.02 1.03]
  [0.04 1.05]]

 [[2.06 3.07]
  [2.08 3.09]
  [2.1  3.11]]

 [[4.12 5.13]
  [4.14 5.15]
  [4.16 5.17]]]


Mismatched dimensions cause an error.

In [49]:
try:
  x = np.random.random((3,3,4))+np.random.random((3,2,4))
except ValueError as e:
  print(e)

operands could not be broadcast together with shapes (3,3,4) (3,2,4) 


## Saving and Loading

### Saving and loading a single NumPy array

In [ ]:
# Save single array
x = np.random.random((5,))
print(x)

np.save('tmp.npy', x)

In [ ]:
# Load the array
y = np.load('tmp.npy')

print(y)

### Saving and loading a dictionary of NumPy arrays

In [ ]:
# Save dictionary of arrays
x1 = np.random.random((2,))
y1 = np.random.random((3,))
print(x1, y1)

np.savez('tmp.npz', x=x1, y=y1)

In [ ]:
# Load the dictionary of arrays
data = np.load('tmp.npz')

print(data['x'])
print(data['y'])

### PyTorch Conversions

To download go to https://pytorch.org/get-started/locally/ and select your installation preference from the options available.

In [50]:
import torch

# Create a PyTorch Tensor
W = torch.tensor([[1, 1, 1],
                 [2, 2, 2],
                 [3, 3, 3]], dtype=torch.int)

# choose dtype from any of the following available at https://pytorch.org/docs/stable/tensors.html
W

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]], dtype=torch.int32)

In [51]:
# Convert Tensor to an array/matrix
W_arr = W.numpy()

# Convert a array/matrix to a Tensor
W_tensor = torch.tensor(W_arr)

W_arr, W_tensor

(array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]], dtype=int32), tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]], dtype=torch.int32))

## References

You can find a more complete introduction at https://docs.scipy.org/doc/numpy/user/quickstart.html

The following links were helpful in preparing this notebook:

- https://docs.scipy.org/doc/numpy/reference/index.html
- https://github.com/cmudeeplearning11785/deep-learning-tutorials/blob/master/recitation-2/Tutorial-numpy.ipynb
- http://cs231n.github.io/python-numpy-tutorial/#numpy
- https://pytorch.org/docs/stable/index.html
- https://pytorch.org/tutorials/beginner/ptcheat.html